# Generated by Django 6.0.7 on 2026-08-04 05:32

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_login_data(apps, schema_editor):
    Rol = apps.get_model('cuentas', 'Rol')
    Institucion = apps.get_model('cuentas', 'Institucion')
    Usuario = apps.get_model('cuentas', 'Usuario')

    roles = {}
    for tipo_rol in ['ADMINISTRADOR', 'DOCENTE', 'ESTUDIANTE']:
        rol, _ = Rol.objects.get_or_create(tipo_rol=tipo_rol)
        roles[tipo_rol] = rol

    institucion, _ = Institucion.objects.get_or_create(
        dominio='umes',
        defaults={'nombre': 'UMES'},
    )

    Usuario.objects.get_or_create(
        institucion=institucion,
        usuario='admin',
        defaults={
            'contrasena_hash': make_password('Admin123!'),
            'rol': roles['ADMINISTRADOR'],
            'activo': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_login_data, migrations.RunPython.noop),
    ]
