# Generated by Django 6.0.7 on 2026-08-05 00:21

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_test_users(apps, schema_editor):
    Institucion = apps.get_model('cuentas', 'Institucion')
    Rol = apps.get_model('cuentas', 'Rol')
    Usuario = apps.get_model('cuentas', 'Usuario')

    institucion = Institucion.objects.get(dominio='umes')
    docente = Rol.objects.get(tipo_rol='DOCENTE')
    estudiante = Rol.objects.get(tipo_rol='ESTUDIANTE')

    Usuario.objects.get_or_create(
        institucion=institucion,
        usuario='docente',
        defaults={
            'contrasena_hash': make_password('Docente123!'),
            'rol': docente,
            'activo': True,
        },
    )
    Usuario.objects.get_or_create(
        institucion=institucion,
        usuario='estudiante',
        defaults={
            'contrasena_hash': make_password('Estudiante123!'),
            'rol': estudiante,
            'activo': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_seed_login_data'),
    ]

    operations = [
        migrations.RunPython(seed_test_users, migrations.RunPython.noop),
    ]
