# Generated by Django 6.0.7 on 2026-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(db_column='id_anuncio', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anuncio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(db_column='id_asistencia', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], max_length=15)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(db_column='id_aula', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(db_column='id_carrera', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarreraSemestre',
            fields=[
                ('id_carrera_semestre', models.AutoField(db_column='id_carrera_semestre', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'carrera_semestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CicloAcademico',
            fields=[
                ('id_ciclo', models.AutoField(db_column='id_ciclo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'ciclo_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='id_curso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(db_column='id_docente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('id_usuario', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(db_column='id_entrega', primary_key=True, serialize=False)),
                ('archivo', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(db_column='id_estudiante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('carne', models.CharField(max_length=20)),
                ('id_usuario', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteSeccion',
            fields=[
                ('id_estudiante_seccion', models.AutoField(db_column='id_estudiante_seccion', primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estudiante_seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(db_column='id_facultad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'facultad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(db_column='id_horario', primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sabado')], max_length=10)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(db_column='id_institucion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('dominio', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(db_column='id_modulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(db_column='id_nota', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'nota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id_pensum', models.AutoField(db_column='id_pensum', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pensum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(db_column='id_recurso', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('ENLACE', 'Enlace'), ('VIDEO', 'Video')], max_length=20)),
                ('url_o_archivo', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(db_column='id_seccion', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id_semestre', models.AutoField(db_column='id_semestre', primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'semestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SesionVirtual',
            fields=[
                ('id_sesion_virtual', models.AutoField(db_column='id_sesion_virtual', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('enlace', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'sesion_virtual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(db_column='id_tarea', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
    ]
